Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -1,4 +1,5 @@
 #!/bin/bash
+
 # ANSI color codes
 RED='\033[0;31m'
 GREEN='\033[0;32m'
@@ -9,59 +10,60 @@ NC='\033[0m' # No Color
 
 # Function to display a progress bar
 fun_bar() {
-    comando[0]="$1"
-    comando[1]="$2"
+    local comando=("$1" "$2")
     
     (
-    [[ -e $HOME/fim ]] && rm $HOME/fim
+    [[ -e $HOME/fim ]] && rm "$HOME/fim"
     ${comando[0]} -y > /dev/null 2>&1
     ${comando[1]} -y > /dev/null 2>&1
-    touch $HOME/fim
+    touch "$HOME/fim"
     ) > /dev/null 2>&1 &
     
     tput civis
-    echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
+    echo -ne "  ${BOLD}${YELLOW}◇ PLEASE WAIT... ${NC}- ${BOLD}${YELLOW}["
     while true; do
         for ((i=0; i<18; i++)); do
-            echo -ne "\033[1;31m#"
+            echo -ne "${BOLD}${RED}#"
             sleep 0.1s
         done
-        [[ -e $HOME/fim ]] && rm $HOME/fim && break
-        echo -e "\033[1;33m]"
+        [[ -e $HOME/fim ]] && rm "$HOME/fim" && break
+        echo -e "${BOLD}${YELLOW}]"
         sleep 1s
         tput cuu1
         tput dl1
-        echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
+        echo -ne "  ${BOLD}${YELLOW}◇ PLEASE WAIT... ${NC}- ${BOLD}${YELLOW}["
     done
-    echo -e "\033[1;33m]\033[1;37m -\033[1;32m◇ DONE!\033[1;37m"
+    echo -e "${BOLD}${YELLOW}]${NC} -${BOLD}${GREEN}◇ DONE!${NC}"
     tput cnorm
 }
 
 # Function to verify key
 verif_key() {
+    local krm
     krm=$(echo '5:q-3gs2.o7%8:1'|rev)
-    chmod +x $_Ink/list > /dev/null 2>&1
+    chmod +x "$_Ink/list" > /dev/null 2>&1
     [[ ! -e "$_Ink/list" ]] && {
-        echo -e "\n\033[1;31m◇ KEY INVALID!\033[0m"
-        rm -rf $HOME/hehe > /dev/null 2>&1
+        echo -e "\n${BOLD}${RED}◇ KEY INVALID!${NC}"
+        rm -rf "$HOME/hehe" > /dev/null 2>&1
         sleep 2
         clear
         exit 1
     }
 }
 
-
-
 # Function to generate random code and send to Telegram handle
 send_code_telegram() {
     local telegram_handle=$1
+    local random_code
     random_code=$(shuf -i 100000-999999 -n 1)  # Generate random 6-digit code
+    local expiration_date
     expiration_date=$(date -d "+24 hours" +"%Y-%m-%d %H:%M:%S")  # Expiration date is set to 24 hours from now
+    local message
     message="Your verification code for installation is: $random_code\nThis code will expire on: $expiration_date"
 
     # Replace YOUR_BOT_TOKEN and YOUR_CHAT_ID with your actual bot token and chat ID
-    bot_token="6803390472:AAEEX8hpTFhsxbmzU5oiZD4dYCOKxS4-lCE"
-    chat_id="5989863155"
+    local bot_token="6803390472:AAEEX8hpTFhsxbmzU5oiZD4dYCOKxS4-lCE"
+    local chat_id="5989863155"
 
     # Send message to Telegram
     curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" -d "chat_id=$chat_id" -d "text=$message" > /dev/null
@@ -71,15 +73,15 @@ clear
 
 # Check for root privilege
 [[ "$(whoami)" != "root" ]] && {
-    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
-    rm $HOME/hehe > /dev/null 2>&1
+    echo -e "${BOLD}${YELLOW}[${BOLD}${RED}Erro${BOLD}${YELLOW}] ${NC}- ${BOLD}${YELLOW}◇ YOU NEED TO RUN AS ROOT!${NC}"
+    rm "$HOME/hehe" > /dev/null 2>&1
     exit 0
 }
 
 send_code_telegram
 
 # Prompt the user to enter the verification code
-msg -bar2
+echo -e "\n${BOLD}${YELLOW}◇───────────────────────────────────────────────────◇${NC}"
 figlet " -MAPTECHGH- " | lolcat
 echo "Contact @maptechgh on telegram for verification."
 echo  # Add a newline for spacing
@@ -101,13 +103,19 @@ _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
 # Function to calculate remaining time until expiration
 calculate_remaining_time() {
     local expiration_time="$1"
-    local current_time=$(date +%s)
-    local expiration_seconds=$(date -d "$expiration_time" +%s)
-    local remaining_seconds=$((expiration_seconds - current_time))
+    local current_time
+    current_time=$(date +%s)
+    local expiration_seconds
+    expiration_seconds=$(date -d "$expiration_time" +%s)
+    local remaining_seconds
+    remaining_seconds=$((expiration_seconds - current_time))
 
-    local hours=$((remaining_seconds / 3600))
-    local minutes=$(( (remaining_seconds % 3600) / 60 ))
-    local seconds=$((remaining_seconds % 60))
+    local hours
+    hours=$((remaining_seconds / 3600))
+    local minutes
+    minutes=$(( (remaining_seconds % 3600) / 60 ))
+    local seconds
+    seconds=$((remaining_seconds % 60))
 
     echo "$hours hours $minutes minutes $seconds seconds"
 }
@@ -115,31 +123,32 @@ calculate_remaining_time() {
 # Display the countdown timer
 display_countdown_timer() {
     local expiration_time="$1"
-    local remaining_time=$(calculate_remaining_time "$expiration_time")
+    local remaining_time
+    remaining_time=$(calculate_remaining_time "$expiration_time")
 
     echo -e "\nPassword will expire in: $remaining_time"
 }
 
 # Display countdown timer
-    display_countdown_timer "$expiration_date"
+display_countdown_timer "$expiration_date"
 
 # Welcome message
-echo -e "\033[1;31m\033[0m"
+echo -e "${BOLD}${RED}${NC}"
 tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "◇─────────ㅤ🌍ㅤWelcome To MAPTECH VPS MANAGERㅤ🌍ㅤ─────────◇" ; tput sgr0
 echo ""
-echo -e "\033[1;33mㅤTHIS SCRIPT CONTAINS THE FOLLOWING!!\033[0m"
+echo -e "${BOLD}${YELLOW}ㅤTHIS SCRIPT CONTAINS THE FOLLOWING!!${NC}"
 echo ""
-echo -e "\033[1;33m◇ \033[1;32mINSTALL A SET OF SCRIPTS AS TOOLS FOR\033[0m"
+echo -e "${BOLD}${YELLOW}◇ ${BOLD}${GREEN}INSTALL A SET OF SCRIPTS AS TOOLS FOR${NC}"
 echo ""
-echo -e "\033[1;33m◇  \033[1;32mNETWORK, SYSTEM AND USER MANAGEMENT.\033[0m"
-echo -e "\033[1;33m◇  \033[1;32mEASY INTERFACE FOR BEGINNERS.\033[0m"
+echo -e "${BOLD}${YELLOW}◇  ${BOLD}${GREEN}NETWORK, SYSTEM AND USER MANAGEMENT.${NC}"
+echo -e "${BOLD}${YELLOW}◇  ${BOLD}${GREEN}EASY INTERFACE FOR BEGINNERS.${NC}"
 echo ""
-echo -e "\033[1;31m◇──────────────ㅤ🌍ㅤMAPTECH VPS MANAGERㅤ🌍ㅤ──────────────◇\033[0m"
+echo -e "${BOLD}${RED}◇──────────────ㅤ🌍ㅤMAPTECH VPS MANAGERㅤ🌍ㅤ──────────────◇${NC}"
 echo ""
 
 # Prompt to continue
-echo -ne "\033[1;36m◇ Do you want to continue? [Y/N]: \033[1;37m"
-read x
+echo -ne "${BOLD}${CYAN}◇ Do you want to continue? [Y/N]: ${NC}"
+read -r x
 [[ $x = @(n|N) ]] && exit
 
 # Modify SSH configuration and restart service
@@ -147,7 +156,7 @@ sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
 service ssh restart  > /dev/null 2>&1
 
 # Key Verification
-echo -e "\n\033[1;36m◇ CHECKING...(It Take Some Time Please Wait!)\033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/AVEGAH/MAPTECH-VPS-MANAGER/main/Install/list > /dev/null 2>&1; verif_key
+echo -e "\n${BOLD}${CYAN}◇ CHECKING...(It Take Some Time Please Wait!)\033[1;37m 16983:16085${NC}" ; rm "$_Ink/list" > /dev/null 2>&1; wget -P "$_Ink" https://raw.githubusercontent.com/AVEGAH/MAPTECH-VPS-MANAGER/main/Install/list > /dev/null 2>&1; verif_key
 sleep 3s
 
 # Update system
@@ -159,35 +168,35 @@ wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
 > /dev/null 2>&1
 rm 2lHZ43 > /dev/null 2>&1
 # Prompt to keep or create user database
-echo -e "\n\033[1;32m◇ KEY VALID!\033[1;32m"
+echo -e "\n${BOLD}${GREEN}◇ KEY VALID!${BOLD}${GREEN}"
 sleep 1s
 echo ""
 [[ -f "$HOME/usuarios.db" ]] && {
     clear
-    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo -e "\n${BOLD}${BLUE}◇───────────────────────────────────────────────────◇${NC}"
     echo ""
-    echo -e "                 \033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
+    echo -e "                 ${BOLD}${YELLOW}• ${BOLD}${RED}◇ ATTENTION!${BOLD}${YELLOW}• ${NC}"
     echo ""
-    echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mwas"
+    echo -e "${BOLD}${YELLOW}A User Database ${BOLD}${GREEN}(usuarios.db) ${BOLD}${YELLOW}was"
     echo -e "Found! Want to keep it by preserving the limit"
     echo -e "of Simutanea connections of users ? Or Want"
-    echo -e "create a new database?\033[0m"
-    echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Database Current\033[0m"
-    echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
-    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo -e "create a new database?${NC}"
+    echo -e "\n${BOLD}${WHITE}[${BOLD}${RED}1${BOLD}${WHITE}] ${BOLD}${YELLOW}Keep Database Current${NC}"
+    echo -e "${BOLD}${WHITE}[${BOLD}${RED}2${BOLD}${WHITE}] ${BOLD}${YELLOW}Create a New Database${NC}"
+    echo -e "\n${BOLD}${BLUE}◇───────────────────────────────────────────────────◇${NC}"
     echo ""
     tput setaf 2 ; tput bold ; read -p "Option ?: " -e -i 1 optiondb ; tput sgr0
 } || {
-    awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+    awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > "$HOME/usuarios.db"
 }
-[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > "$HOME/usuarios.db"
 clear
 tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "◇ WAIT FOR INSTALLATION." ; tput sgr0
 echo ""
 echo ""
-echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ UPDATING SYSTEM...\033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+echo -e "          ${BOLD}${YELLOW}[${BOLD}${RED}!${BOLD}${YELLOW}] ${BOLD}${GREEN}◇ UPDATING SYSTEM...${BOLD}${YELLOW}[${BOLD}${RED}!${BOLD}${YELLOW}]${NC}"
 echo ""
-echo -e "    \033[1;33m◇ UPDATES USUALLY TAKE A LITTLE TIME!\033[0m"
+echo -e "    ${BOLD}${YELLOW}◇ UPDATES USUALLY TAKE A LITTLE TIME!${NC}"
 echo ""
 fun_attlist () {
     apt-get update -y
@@ -197,14 +206,15 @@ fun_attlist () {
 fun_bar 'fun_attlist'
 clear
 echo ""
-echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ INSTALLING PACKAGES\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo -e "          ${BOLD}${YELLOW}[${BOLD}${RED}!${BOLD}${YELLOW}] ${BOLD}${GREEN}◇ INSTALLING PACKAGES${BOLD}${YELLOW}[${BOLD}${RED}!${BOLD}${YELLOW}] ${NC}"
 echo ""
-echo -e "\033[1;33m◇ SOME PACKAGES ARE EXTREMELY NECESSARY!\033[0m"
+echo -e "${BOLD}${YELLOW}◇ SOME PACKAGES ARE EXTREMELY NECESSARY!${NC}"
 echo ""
 inst_pct () {
-    _pacotes=("bc" "apache2" "cron" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python" "python3" "python-pip")
-    for _prog in ${_pacotes[@]}; do
-        apt install $_prog -y
+    local _prog
+    local _pacotes=("bc" "apache2" "cron" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python" "python3" "python-pip")
+    for _prog in "${_pacotes[@]}"; do
+        apt install "$_prog" -y
     done
     pip install speedtest-cli
 }
@@ -212,21 +222,21 @@ fun_bar 'inst_pct'
 [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
 clear
 echo ""
-echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ FINISHING...\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo -e "              ${BOLD}${YELLOW}[${BOLD}${RED}!${BOLD}${YELLOW}] ${BOLD}${GREEN}◇ FINISHING...${BOLD}${YELLOW}[${BOLD}${RED}!${BOLD}${YELLOW}] ${NC}"
 echo ""
-echo -e "      \033[1;33m◇ COMPLETING FUNCTIONS AND SETTINGS!\033[0m"
+echo -e "      ${BOLD}${YELLOW}◇ COMPLETING FUNCTIONS AND SETTINGS!${NC}"
 echo ""
 fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
 clear
 echo ""
-cd $HOME
+cd "$HOME" || exit
 IP=$(wget -qO- ipv4.icanhazip.com)
-echo -e "        \033[1;33m  \033[1;32m◇ INSTALLATION COMPLETED.◇\033[1;33m  \033[0m"
+echo -e "        ${BOLD}${YELLOW}  ${BOLD}${GREEN}◇ INSTALLATION COMPLETED.${BOLD}${YELLOW}  ${NC}"
 echo ""
-echo -e "\033[1;31m\033[1;33m◇ MAIN COMMAND:- \033[1;32mmenu\033[0m"
-echo -e "\033[1;33m◇ MORE INFORMATION \033[1;31m(\033[1;36m◇ TELEGRAM\033[1;31m): \033[1;37m@MAPTECH_VPS_MANAGER \033[1;31m( \033[1;36m @maptechgh \033[1;31m )\033[0m"
+echo -e "${BOLD}${RED}${NC}◇ MAIN COMMAND:- ${BOLD}${GREEN}menu${NC}"
+echo -e "${BOLD}${YELLOW}◇ MORE INFORMATION ${BOLD}${RED}(${BOLD}${CYAN}◇ TELEGRAM${BOLD}${RED}): ${BOLD}${WHITE}@MAPTECH_VPS_MANAGER ${BOLD}${RED}( ${BOLD}${CYAN} @maptechgh ${BOLD}${RED} )${NC}"
 echo -e ""
-echo -e "\033[1;31m \033[1;33m◇--TIP!--◇\033[1;36mㅤ--Using this url you can easily see the number of users online at the server.\033[0m"
+echo -e "${BOLD}${RED} ${BOLD}${YELLOW}◇--TIP!--◇${BOLD}${CYAN}ㅤ--Using this url you can easily see the number of users online at the server.${NC}"
 echo -e " http://$IP:8888/server/online"
 echo -e ""
-rm $HOME/hehe && cat /dev/null > ~/.bash_history && history -c
+rm "$HOME/hehe" && cat /dev/null > ~/.bash_history && history -c
